name: CI

# main 브랜치에 push 또는 PR이 열릴 때마다 동작
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest

    # env:
    #   vcpkg가 이미 시스템에 설치되어 있으면 이 줄은 없어도 됩니다.
    #   VCPKG_ROOT: ${{ runner.workspace }}/vcpkg

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Install dependencies with vcpkg
        run: |
          vcpkg install sdl2:x64-windows
          vcpkg install sdl2-ttf:x64-windows
          vcpkg install sdl2-image:x64-windows
          vcpkg install gtest:x64-windows
          vcpkg install benchmark:x64-windows

      - name: Integrate vcpkg with MSBuild
        run: vcpkg integrate install

      - name: Build solution
        run: msbuild MyPuzzle.sln /p:Configuration=Release /p:Platform=x64

      - name: Run unit tests
        working-directory: .
        run: x64\Release\Puzzle.Tests.exe --gtest_output="xml;Tests.xml"

      - name: Run benchmarks
        working-directory: .
        run: x64\Release\Puzzle.Benchmarks.exe --benchmark_format=json --benchmark_out="Benchmarks.json"

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: Tests.xml

      - name: Upload benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results
          path: Benchmarks.json
