name: CI

# main 브랜치에 push 또는 PR이 열릴 때마다 동작
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Restore vcpkg cache
        id: cache-vcpkg
        uses: actions/cache/restore@v4
        with:
          path: 
            - vcpkg_installed
            - C:/vcpkg/installed
            - C:/vcpkg/downloads
          key: ${{ runner.os }}-vcpkg-${{ hashFiles('vcpkg.json') }}
          restore-keys: ${{ runner.os }}-vcpkg-

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Install dependencies with vcpkg manifest
        run: |
          bootstrap-vcpkg.bat
          vcpkg install --triplet x64-windows
          vcpkg integrate install

      - name: Save vcpkg_installed cache
        id: cache-vcpkg-save
        if: always()
        uses: actions/cache/save@v4
        with:
          path: 
            - vcpkg_installed
            - C:/vcpkg/installed
            - C:/vcpkg/downloads
          key: ${{ steps.cache-vcpkg.outputs.cache-primary-key }}

      - name: Build solution
        run: msbuild MyPuzzle.sln /p:Configuration=Release /p:Platform=x64

      - name: Run unit tests
        working-directory: .
        run: x64\Release\Puzzle.Tests.exe --gtest_output="json:Tests.json"

      - name: Run benchmarks
        working-directory: .
        run: x64\Release\Puzzle.Benchmarks.exe --benchmark_format=json --benchmark_out="Benchmarks.json"

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: Tests.json

      - name: Upload benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results
          path: Benchmarks.json
