name: CI

# main 브랜치에 push 또는 PR이 열릴 때마다 동작
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache vcpkg
        uses: actions/cache@v4
        with:
          path: vcpkg_installed
          key: ${{ runner.os }}-vcpkg-${{ hashFiles('vcpkg.json') }}
          restore-keys: |
              ${{ runner.os }}-vcpkg-
        
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Install dependencies with vcpkg
        run: |
          IF NOT EXIST C:/vcpkg ( git clone https://github.com/Microsoft/vcpkg.git C:/vcpkg )
          bootstrap-vcpkg.bat
          vcpkg install sdl2:x64-windows
          vcpkg install sdl2-ttf:x64-windows
          vcpkg install sdl2-image:x64-windows
          vcpkg install gtest:x64-windows
          vcpkg install benchmark:x64-windows

      - uses: actions/cache@v4
        name: Cache build outputs
        with:
          path: x64/Release
          key: ${{ runner.os }}-build-${{ hashFiles('**/*.cpp','**/*.h') }}
        
      - name: Integrate vcpkg with MSBuild
        run: vcpkg integrate install

      - name: Build solution
        run: msbuild MyPuzzle.sln /p:Configuration=Release /p:Platform=x64

      - name: Run unit tests
        working-directory: .
        run: x64\Release\Puzzle.Tests.exe --gtest_output="json:Tests.json"

      - name: Run benchmarks
        working-directory: .
        run: x64\Release\Puzzle.Benchmarks.exe --benchmark_format=json --benchmark_out="Benchmarks.json"

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: Tests.json

      - name: Upload benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results
          path: Benchmarks.json
